"use client";

import Link from "next/link";
import Logo from "@/components/Logo";

import Footer from "@/components/Footer";
export default function TermsAndConditionsPage() {
  return (
    <div style={{ background: "var(--surface-2b)", minHeight: "100vh", color: "var(--text-secondary-strong)" }}>
      {/* Header */}
      <div style={{ borderBottom: "1px solid var(--border-inset)", padding: "20px 0" }}>
        <div style={{ maxWidth: 900, margin: "0 auto", padding: "0 24px", display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <Link href="/">
            <Logo width={150} height={32} className="legal-logo" />
          </Link>
          <Link href="/" style={{ color: "var(--text-secondary)", fontSize: 14, textDecoration: "none" }}>
            &larr; Back to Home
          </Link>
        </div>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 900, margin: "0 auto", padding: "60px 24px 80px" }}>
        <h1 style={{ color: "var(--text-primary)", fontSize: 36, fontWeight: 700, marginBottom: 8 }}>Terms Of Use</h1>
        <p style={{ color: "var(--text-tertiary)", fontSize: 14, marginBottom: 40 }}>Last updated: March 2025</p>

        <div className="legal-content">
          <p>
            This terms of use (&quot;Terms of Use&quot;) govern your use of our website{" "}
            <a href="https://app.walnutai.ai/" target="_blank" rel="noopener noreferrer">https://app.walnutai.ai/</a>{" "}
            (&quot;Platform&quot;) and product offered through the Platform (hereinafter collectively referred to as &quot;Services&quot;) which are owned, controlled and operated by Simplify3x Software Private Limited, a company incorporated under the laws of India, and having its registered office at Ground Floor, BCIT, Bhartiya City, RK Hegde Nagar, Bengaluru, Karnataka 560064 (&quot;Company&quot; or &quot;WalnutAI&quot;).
          </p>
          <p>
            By accessing or using either or both the Services, you signify that you have read, understood and agree to be bound by these Terms of Use. If you do not agree with these Terms of Use, please do not access and/or use the Services.
          </p>
          <p>
            These Terms of Use will be treated as an &apos;electronic record&apos; as defined under the Information Technology Act, 2000 and the rules made thereunder (as modified from time to time). Further, these Terms of Use are published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediary Guidelines and Digital Media Ethics Code) Rules, 2021. You hereby explicitly acknowledge that this electronic record is generated by a computer system and does not require any physical or digital signatures.
          </p>
          <p>
            For the purposes of these Terms of Use, &quot;we&quot;, &quot;our&quot; and &quot;us&quot; shall mean the Company and &quot;you&quot; and &quot;your&quot;, shall mean a user of the Services, whether registered or not (&quot;User&quot;).
          </p>

          <h2>License Grant and Restrictions</h2>
          <p><strong>License Grant:</strong> Subject to this Agreement, during your applicable Subscription Term, we grant you a non-exclusive, non-sublicensable, and non-transferable license under our intellectual property rights to the Service as follows:</p>
          <ul>
            <li><strong>For Cloud Service:</strong> You and your Users may access and use the Cloud Service.</li>
            <li><strong>For On Premise:</strong> You may deploy, operate, and use the Software within your computing environment, and your Users may access and use the Software as deployed by you.</li>
          </ul>

          <p><strong>Authorized Use:</strong> You may only use the Service: (a) within the defined Scope of Use outlined in your Order; and (b) to support the internal operations of (i) your and your Affiliates&apos; businesses, and (ii) Your Customers, but only as part of the services you provide to them (and not as a standalone product or service).</p>

          <p><strong>Documentation:</strong> You may make a reasonable number of copies of the Documentation solely as necessary to use the Service in accordance with this Agreement. You must include all our proprietary notices on all copies.</p>

          <p><strong>Use by Affiliates, Contractors, and Customers:</strong> Only Users may access the Service. You may add your Affiliates, contractors, and Your Customers as Users (&quot;Additional Users&quot;), provided that:</p>
          <ul>
            <li>Each Additional User&apos;s use is subject to this Agreement, and you are responsible for their compliance.</li>
            <li>Contractors may only use the Service on your behalf to provide services to you.</li>
            <li>Your customers may only use the Service as part of the services you provide to them, solely in relation to your products and services.</li>
          </ul>

          <p><strong>Service Delivery and Activation:</strong> Activation of the Cloud Service will occur upon the creation of an account for the Cloud Service for your use. Delivery of the Software will occur via a download link for the installation package and instructions, which you will receive upon execution of the applicable Order. Software license files and activation will be provided once you furnish us with your machine ID. You are responsible for providing this ID so we can generate your license file.</p>

          <p><strong>Ownership and Restrictions:</strong> As between the parties, we exclusively own and retain all right, title, and interest in and to the Licensed Materials, our Confidential Information, and the System Data. All rights not expressly granted to you are reserved by us and our licensors. Without limiting the generality of the foregoing and except as otherwise expressly permitted in this Agreement, you will not:</p>
          <ul>
            <li>Distribute copies of the Licensed Materials, in whole or in part, to any third party;</li>
            <li>Use the Licensed Materials for the benefit of any third party, or permit any third party to use the Licensed Materials (except as expressly permitted with respect to your Additional Users);</li>
            <li>Copy, modify, or create derivative works of the Licensed Materials;</li>
            <li>Reverse engineer, disassemble, decompile, translate or otherwise attempt to derive the source code, underlying ideas, algorithms, file formats or non-public APIs to the Service;</li>
            <li>Remove or obscure any proprietary or other notices on the Licensed Materials;</li>
            <li>Attempt to gain unauthorized access to the Licensed Materials, circumvent any security measures, or interfere with any mechanisms intended to limit your use;</li>
            <li>Use the Licensed Materials for competitive analysis, product benchmark or to build competing products;</li>
            <li>Publicly disseminate information about the performance of the Licensed Materials;</li>
            <li>Use the Licensed Materials to transmit or store any malicious code, files, scripts, agents or programs intended to do harm;</li>
            <li>Encourage or assist any third party to do any of the foregoing.</li>
          </ul>

          <h2>Permitted Users</h2>
          <p>
            You represent and warrant that you have the legal capacity and authority to agree to and accept these Terms of Use on behalf of yourself and any person you purport to represent, being either a company, partnership firm, sole proprietorship or any other organisation, and access the Services on its behalf as a result of being duly authorized by way of necessary corporate action.
          </p>
          <p>You shall not access and/or use the Services if you are not competent to contract under the applicable laws, rules and regulations.</p>
          <p>Persons below the age of 18 (eighteen) years shall use the Service only under strict guidance and supervision of their parents/guardians.</p>

          <h2>Access</h2>
          <p>
            Subject to the terms hereof, WalnutAI grants you permission to use the Services as set forth in this Terms of Use, provided that: (i) you will not copy or distribute, any part of the Services in any medium or in any manner whatsoever without WalnutAI&apos;s explicit authorisation in this regard; (ii) you will not alter or modify any part of the Services; and (iii) you will comply with these Terms of Use.
          </p>
          <p>
            In order to access and use the Product, you will need to register on the Platform and create a &quot;User&quot; account. Your account gives you access to the Product and its functionality that we may establish and maintain from time to time and in our sole discretion on the Platform.
          </p>
          <p>
            You must provide your full legal name, valid email address and any other information requested from you, from time to time, in order to complete the registration process and be entitled to use the Product. The Company is not under any obligation to verify the actual identity or authority of the User.
          </p>
          <p>
            Upon completing the registration process, you will be provided with a user identification code, password, or any other piece of information, as part of our security procedures. You must treat such information as confidential, and you must not disclose it to any third party. You also agree to ensure that you will exit/log out from your account at the end of each session. You are solely responsible and liable for any use and misuse of your identification and password and for all activities that occur under your login name and password.
          </p>
          <p>By completing the registration process, you warrant that:</p>
          <ul>
            <li>All the data provided by you is accurate and complete;</li>
            <li>You shall maintain the accuracy of such information, and any changes thereto by regularly updating such information;</li>
            <li>You affirm that you are fully able and competent to enter into the terms, conditions, obligations, affirmations, representations, and warranties set forth in these Terms of Use, and to abide by and comply with this Terms of Use;</li>
            <li>You are eligible in accordance with applicable laws to enter into a binding contract and are not a person barred from receiving the Product under applicable laws.</li>
          </ul>
          <p>
            You are responsible for making all arrangements necessary for you to have access to the Services. You are also responsible for ensuring that any persons who use the Product through your account are aware of these terms, and that they comply with them.
          </p>
          <p>
            We have the right to disable any User identification code or password, whether chosen by you or allocated by us, at any time, if in our opinion you have failed to comply with any of the provisions of these Terms of Use. You will immediately notify WalnutAI of any unauthorized use of your password or user identification code.
          </p>

          <h2>Fees and Payment</h2>
          <p>
            The Company shall charge you fees for your use of the Product (&quot;Fees&quot;). The Company may, at its discretion, modify the Fees from time to time. In the event the Company increases the Fees, we may give you at least 30 (thirty) days&apos; notice and such increase in the Fees will be applicable on your next renewal.
          </p>
          <p>
            Subsequent to payment of the Fees, you may choose not to use the Services. However, even under such circumstances, any and all Fees paid by you to the Company shall be non-refundable.
          </p>
          <p>
            You agree and understand that you will be redirected to third-party payment gateway websites in order to avail the Product. You agree, understand and confirm that the debit card/credit card/net banking/payment wallet details provided by you will be correct and accurate, and you shall not use any debit card/credit card/net banking/payment wallet account which you are unauthorized to lawfully use.
          </p>
          <p>
            You agree to fully cooperate with us in an effort to resolve any problems we encounter while processing your requested order. We will not have the obligation to provide the Product in the event the payment transaction fails, and the appropriate amount is not duly received.
          </p>

          <h2>Cancellation Policy</h2>
          <p>You may cancel your subscription or plan at any time. Upon cancellation:</p>
          <ul>
            <li>You will continue to have access to the Services until the end of your current billing period.</li>
            <li>No refunds will be provided for any fees already paid or for any unused portion of the billing period.</li>
            <li>You will be charged only for the usage and fees that have accrued up to the date of cancellation.</li>
            <li>After the end of the billing period, no further charges will be applied unless you re-subscribe.</li>
          </ul>
          <p>Cancellation may be completed through your account dashboard or by contacting the Company through the designated support channels.</p>

          <h2>Ownership of the Services</h2>
          <p>
            You agree and acknowledge that the Company has the worldwide ownership of the software code, models, training methodology, process flows, products of training, proprietary technology, technical know-how, software tools, controls, designs, algorithms, analyses, class libraries, text, objects, documentation, and anything in relation to the Services and all the trademarks, copyright and any other intellectual property rights of any nature in the Services.
          </p>
          <p>
            Subject to these Terms of Use, you may access and/or avail of the Services, for your requirements only. You are not entitled to duplicate, distribute, create derivative works of, display, or commercially exploit any intellectual property rights associated with the Services features or facilities, directly or indirectly, without our prior written permission.
          </p>

          <h2>Use of the Services</h2>
          <p>
            The Services are made available to you for your lawful use only. As a condition of your use/access of the Services, you represent and warrant to the Company that you will not use/access the Services for any purpose that is unlawful, illegal and/or prohibited by these terms, conditions and notices.
          </p>
          <p>Your use of the Services must:</p>
          <ul>
            <li>Be in accordance with these Terms of Use;</li>
            <li>Be lawful and must comply with all applicable domestic and foreign laws, regulations, rules and policies;</li>
            <li>Be only for purposes that are consistent with the spirit and intended purpose of the Services;</li>
            <li>Not infringe the legal rights of any other person, including but not limited to intellectual property rights, proprietary rights, privacy, publicity and personality rights;</li>
            <li>Not be used with any action, device, software or routine that could directly or indirectly, interfere (or attempt to interfere) with the proper working of the Services.</li>
          </ul>

          <h2>Unauthorised Use</h2>
          <p>As a User, you agree not to:</p>
          <ul>
            <li>Access or use the Services in a manner that violates any applicable laws, regulations, or third-party rights;</li>
            <li>Attempt to gain unauthorized access to other user accounts, systems, or networks associated with the Services;</li>
            <li>Interfere with or disrupt the normal operation of the Services, its servers, or networks;</li>
            <li>Engage in any activity that could harm, disable, overburden, or impair the functionality or security of the Services;</li>
            <li>Modify, reverse engineer, decompile, or disassemble the Services or any part thereof;</li>
            <li>Create any derivative works based on the Services without prior written consent from the Company;</li>
            <li>Use the Services for any commercial purposes without obtaining explicit permission from the Company;</li>
            <li>Circumvent or attempt to circumvent any security measures or technological restrictions implemented by the Company;</li>
            <li>Upload, input, publish, transmit, store, update or share any information that is defamatory, obscene, pornographic, paedophilic, invasive of another&apos;s privacy, insulting or harassing on the basis of gender, libellous, racially or ethnically objectionable;</li>
            <li>Forge email headers or otherwise manipulate identifiers in order to disguise the origin of any Input;</li>
            <li>Harvest, collect or store personal information or data of other Users;</li>
            <li>Use the Product to transmit infringing, libelous, or otherwise unlawful or tortious material;</li>
            <li>Use the Product to store or transmit malicious code;</li>
            <li>Remove, from the Services, any logo, copyright or proprietary notices, legends, symbols, labels, watermarks, signatures or any other like marks;</li>
            <li>Use the Product or any part of it to create a false identity, to impersonate any person or organization, or attempt to disguise the origin of any content.</li>
          </ul>

          <h2>User Content</h2>
          <p>
            While using the Product, you may provide various forms of inputs, such as text, image, voice, video or other form of data input (&quot;Input&quot;). You represent and warrant that you have all necessary rights and authority to provide the Input and that it does not violate the intellectual property rights or other rights of any third party.
          </p>
          <p>
            Once the Product receives your Inputs, it will generate content, results, or other output, in the form of text &amp;/or code (&quot;Output&quot;), using certain algorithms and processes (both Input and Output shall be collectively referred to as the &quot;Content&quot;).
          </p>
          <p>
            You agree and acknowledge that the Content shall be owned by you. To the extent possible and permissible by law, the Company hereby assigns to you, the use of all intellectual property rights in and associated with the Output.
          </p>
          <p>You must ensure that the Content uploaded, posted, entered, shared or submitted by you:</p>
          <ul>
            <li>Is not in violation of any laws;</li>
            <li>Is not in violation of anyone&apos;s copyright or intellectual property rights;</li>
            <li>Is not vindictive of or targets any person individually or personally on the Product.</li>
          </ul>
          <p>
            The Company reserves the right to use the Content to train, improve, and further develop the Product. The User explicitly consents to the use of their Input and Output for these purposes. If the User wishes to deny such consent, they may do so in accordance with the Privacy Policy.
          </p>

          <h2>Privacy Policy</h2>
          <p>
            Access to and use of the Services is also subject to the Company&apos;s privacy policy, available at{" "}
            <Link href="/privacy-policy" style={{ color: "var(--accent)" }}>Privacy Policy</Link>. We respect your privacy. The Company will not intentionally monitor or disclose any private messages or address information unless required by law, regulation or court order.
          </p>

          <h2>AI Product Terms</h2>
          <p>
            Our AI Products offer exciting possibilities for content creation and test automation. However, they also involve new, evolving and unsettled legal and business risks. We encourage you to carefully consider these risks before using the AI Products.
          </p>
          <p>Use of AI Products is mostly optional. You must actively choose to enable them. You can turn them off at any time. By enabling or using AI Products, you agree to these terms.</p>

          <h3>Input and Output</h3>
          <p>
            The AI Product provides Output in response to Input. Both Input and Output are considered Your Data, and you retain ownership of them as outlined in this Agreement. We will not use your Input or Output to train our AI Products for other customers.
          </p>
          <p>
            We use technology from third-party service providers (such as OpenAI) to power our AI Products. By using the AI Products, you consent to your Input and Output being shared with and processed by these providers solely for the purpose of providing the AI Products to you. We will contractually obligate such third-party providers to not use Input or Output to train their models.
          </p>
          <p>You agree not to:</p>
          <ul>
            <li>Provide Input that violates any third-party rights or any applicable law, or that is intended to generate Output that does so;</li>
            <li>Use Output in a way that you know, or reasonably should know, violates any third-party rights or any applicable law.</li>
          </ul>

          <h3>Disclaimer</h3>
          <p style={{ fontWeight: 600, color: "var(--text-primary)" }}>
            AI-GENERATED OUTPUT IS PRODUCED BY ARTIFICIAL INTELLIGENCE AND MACHINE LEARNING, WHICH MAY INCLUDE TECHNOLOGY FROM THIRD-PARTY PROVIDERS. WE DO NOT GUARANTEE THE ACCURACY, COMPLETENESS, OR RELIABILITY OF ANY OUTPUT, NOR DO WE GUARANTEE THAT OUTPUT WILL NOT VIOLATE ANY THIRD-PARTY RIGHTS OR LAW. WE ARE NOT LIABLE FOR ANY USE OF AI PRODUCTS OR THEIR OUTPUT.
          </p>
          <p>Due to the nature of AI:</p>
          <ul>
            <li>Output may not be unique, and different users may receive similar or identical Output;</li>
            <li>Output does not represent our views or opinions and is not our professional advice;</li>
            <li>You acknowledge that Output will not be considered Confidential Information under this Agreement;</li>
            <li>You will not (and will ensure your Users do not) represent that Output is human-generated or that it is approved or endorsed by us or our third-party providers.</li>
          </ul>
          <p>You are solely responsible for your use of any Output and for determining its appropriateness for your intended use.</p>

          <h2>Third Party Products</h2>
          <p>
            The Product may include other third-party software and/or applications (&quot;Third Party Products&quot;). The Third-Party Products are not under the control of the Company and the Company has no responsibility or liability for any Third-Party Products, its contents, business, products and services.
          </p>
          <p>
            As part of your usage of the Product, you may have access to certain Open-Source Software. The Company has rights to permit your use of such software as envisaged under these Terms of Use. You can derive access to the licenses governing such Open Source Software by sending an email to{" "}
            <a href="mailto:contact@walnutai.ai">contact@walnutai.ai</a>.
          </p>

          <h2>Indemnity</h2>
          <p>
            You agree to indemnify, defend and hold harmless the Company and all other persons related to, associated or connected with the Company, from and against any and all liabilities, losses, damages, costs and expenses, including without limitation, legal fees, incurred by the Company or such other person in connection with any claim, demand or other action arising out of, related to, or connected with your use of the Services, or your breach of these Terms of Use. This indemnification obligation will survive these Terms of Use.
          </p>

          <h2>Limitation of Liability</h2>
          <p style={{ fontWeight: 600, color: "var(--text-primary)" }}>
            ACCESS TO THESE SERVICES, INCLUDING FEATURES OF THE PRODUCT ARE AVAILABLE TO USE AS A MATTER OF CONVENIENCE. THE COMPANY EXPRESSLY DISCLAIMS ANY CLAIM OR LIABILITY ARISING OUT OF THE CONTENT. YOU AGREE AND ACKNOWLEDGE THAT YOU SHALL BE SOLELY RESPONSIBLE FOR YOUR CONDUCT.
          </p>
          <p style={{ fontWeight: 600, color: "var(--text-primary)" }}>
            IN NO EVENT SHALL THE COMPANY BE LIABLE FOR ANY DIRECT, INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL OR CONSEQUENTIAL DAMAGES OR FOR ANY DAMAGES WHATSOEVER INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF USE, DATA OR PROFITS, ARISING OUT OF OR IN ANY WAY CONNECTED WITH THE ACCESS, USE OR PERFORMANCE OF THE SERVICES, WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE, EVEN IF THE COMPANY HAD BEEN ADVISED OF THE POSSIBILITY OF DAMAGES.
          </p>
          <p>
            In any case, the User acknowledges and agrees that our aggregate liability under these Terms will not exceed the greater of the Fees you paid for availing the Product during the 12 months immediately prior to the date the liability arose. The limitations in this section apply only to the maximum extent permitted by applicable law.
          </p>
          <p>
            <strong>Specific Limitation for Cloud Service Security Incidents:</strong> For Cloud Service only, our total liability for any Security Incident arising from a breach of our security and data protection obligations under this Agreement or a violation of Privacy Laws will not exceed the amount covered by our cyber liability insurance.
          </p>

          <h2>Disclaimer</h2>
          <p>
            You agree that you are availing of the features and facilities at your own risk. The Services are provided on an &quot;AS IS&quot; basis. The Company expressly disclaims all warranties of any kind, whether express or implied, including, but not limited to the implied warranties of merchantability, fitness for a particular purpose and non-infringement.
          </p>
          <p>
            The Company makes no warranty that the features and facilities shall meet your requirements, that the Services shall be uninterrupted and/or timely and/or secure and/or error free; nor does the Company make any warranty as to the results that may be obtained from the use of the features and facilities.
          </p>

          <h3>Output Related Disclaimers</h3>
          <p>
            The Output generated by the Product is based on algorithms and automated processes and is therefore intended for informational purposes only and does not constitute professional advice. The Output may not always accurately reflect real-world scenarios, facts, or circumstances. The Company does not guarantee the correctness, reliability, or accuracy of the Output.
          </p>
          <p>
            You should not solely rely on the Output for any decision-making. It is your responsibility to independently verify any information obtained from the Product and to consult with qualified professionals before making any decisions or taking any actions that could affect your health, financial status, legal rights, education, or any other important aspect of your life.
          </p>

          <h2>Security</h2>
          <p>
            The Company has implemented the necessary technical and organizational measures designed to secure your personal information from accidental loss and from unauthorized access, use, alteration or disclosure. However, the Company cannot guarantee that unauthorized third parties will never be able to overcome such measures or use your personal information for improper purposes. You acknowledge that you provide your personal information at your own risk.
          </p>

          <h2>Termination</h2>
          <p>The Company may, at any time, in its sole discretion, cease to provide the Services to any User.</p>
          <p>
            The Company may, in its sole discretion: (i) without cause, suspend or terminate your Account and your access to the Services without any notice or liability to you or any other person; and/or (ii) immediately suspend or terminate your User account and your access to the Services if you violate or otherwise fail to comply with these Terms of Use.
          </p>
          <p>
            Notwithstanding the termination of these Terms of Use, you shall continue to be bound by these Terms of Use in respect of your prior use of the Services and all matters connected with, relating to or arising from such use.
          </p>

          <h2>Force Majeure</h2>
          <p>
            The Company shall not be liable to the User for failure or delay in the performance of the Services for the time and to the extent such failure or delay is caused by force majeure, or reasons beyond the reasonable control of the Company.
          </p>

          <h2>Amendments</h2>
          <p>
            The Company reserves the right to amend, change and/or modify the terms of these Terms of Use at any time and from time to time in its sole discretion. Such amendments and modifications shall be effective immediately upon posting of the amended/modified agreement on the Product. You agree to review these Terms of Use periodically to be aware of such amendments/modifications and your continued access and/or use of the Product shall be deemed your conclusive acceptance of the amended/modified agreement.
          </p>

          <h2>Assignment</h2>
          <p>
            You may not assign or transfer any rights, obligations, or privileges that you have under these Terms of Use. Subject to the foregoing, these Terms of Use will be binding on your successors or permitted assigns. Any assignment or transfer in violation of this clause will be deemed null and void. However, the Company shall have the right to assign its rights and obligations under these Terms of Use to any third-party.
          </p>

          <h2>Governing Law and Jurisdiction</h2>
          <p>
            These Terms of Use shall be governed in all respects by the laws of India without giving effect to any conflicts of law principles that may require the application of the law of a different state or country.
          </p>
          <p>
            Any action arising from or relating to these Terms of Use must be brought in a competent court of law situated at Bengaluru, India. You agree to resolve disputes only on an individual basis, pursuant to the provisions of these Terms of Use.
          </p>

          <h2>Electronic Communication</h2>
          <p>
            By accepting these Terms of Use, you expressly grant your consent to receive notices and communication electronically from the Company unless expressly intimated to the Company otherwise. Communications shall be posted on the Product and all such communications will be deemed to be in &quot;writing&quot; and received by you when posted thereon.
          </p>

          <h2>Miscellaneous Provisions</h2>
          <ul>
            <li>These Terms of Use constitute the entire agreement between the Company and the User with respect to the subject matter hereof and supersedes and replaces all prior or contemporaneous understandings, agreements or communication, written or oral, regarding such subject matter.</li>
            <li>If any provision of these Terms of Use is held to be invalid or unenforceable, such provision shall be struck from these Terms of Use and the remaining provisions shall be enforced.</li>
            <li>The Company&apos;s failure to act with respect to a breach by you or others of these Terms of Use does not waive the Company&apos;s right to act with respect to subsequent or similar breaches.</li>
          </ul>

          <h2>Contact Us</h2>
          <p>If you should have any suggestions or questions regarding these Terms of Use, please contact the Company:</p>
          <p>
            <strong>Address:</strong> Ground Floor, BCIT, Bhartiya City, RK Hegde Nagar, Bengaluru, Karnataka 560064<br />
            <strong>Email:</strong> <a href="mailto:contact@walnutai.ai">contact@walnutai.ai</a>
          </p>
        </div>
      </div>

      <Footer />
    </div>
  );
}
